### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory' ./errors

### ISSUE THREAD

**Issue by naholyr** [maxkueng/chromium-net-errors#1]
You ``require('./errors')`` but default behavior or ``require`` does not include ``.json`` as a standard extension. You should ``require(`./errors.json')`` to fix this.

**Comment by maxkueng** [comment]
Interesting... This never threw an error on my machine. Thanks for reporting! It's fixed in `chromium-net-errors@1.0.3`
